#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: scripts/sync-from-brick-directory.sh [BRICK_DIRECTORY_ROOT]

Copies verified OpenAPI specs and MCP prompt references from the Brick Directory
source repository into this repo. The source can also be supplied with the
BRICK_DIRECTORY_ROOT environment variable.
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
SOURCE_ROOT=${1:-${BRICK_DIRECTORY_ROOT:-../brick-directory}}
SOURCE_ROOT=$(cd -- "$SOURCE_ROOT" && pwd)

if [[ ! -d "$SOURCE_ROOT/backend" ]]; then
  echo "error: $SOURCE_ROOT does not look like the Brick Directory repo (missing backend/)" >&2
  exit 1
fi

OPENAPI_DEST="$REPO_ROOT/references/openapi"
PROMPTS_DEST="$REPO_ROOT/references/prompts"
mkdir -p "$OPENAPI_DEST" "$PROMPTS_DEST"

copy_file() {
  local src=$1
  local dest=$2
  if [[ ! -f "$src" ]]; then
    echo "error: missing source file: $src" >&2
    exit 1
  fi
  install -m 0644 "$src" "$dest"
}

copy_file "$SOURCE_ROOT/backend/libs/rebrickable-client/src/main/resources/openapi/api-spec.yaml" "$OPENAPI_DEST/rebrickable.yaml"
copy_file "$SOURCE_ROOT/backend/libs/brickset-client/src/main/resources/openapi/api-spec.yaml" "$OPENAPI_DEST/brickset.yaml"
copy_file "$SOURCE_ROOT/backend/libs/brickowl-client/src/main/resources/openapi/api-spec.yaml" "$OPENAPI_DEST/brickowl.yaml"
copy_file "$SOURCE_ROOT/backend/libs/bricklink-client/src/main/resources/openapi/api-spec.yaml" "$OPENAPI_DEST/bricklink.yaml"
copy_file "$SOURCE_ROOT/backend/libs/brickeconomy-client/src/main/resources/openapi/api-spec.yaml" "$OPENAPI_DEST/brickeconomy.yaml"

PROMPTS_SOURCE="$SOURCE_ROOT/backend/apps/brick-directory-mcp-server/src/main/resources/prompts"
if [[ ! -d "$PROMPTS_SOURCE" ]]; then
  echo "error: missing prompts directory: $PROMPTS_SOURCE" >&2
  exit 1
fi

while IFS= read -r -d '' prompt; do
  copy_file "$prompt" "$PROMPTS_DEST/$(basename "$prompt")"
done < <(find "$PROMPTS_SOURCE" -maxdepth 1 -type f -name '*.txt' -print0 | sort -z)

{
  echo "# Source references"
  echo
  echo "Generated by scripts/sync-from-brick-directory.sh. Do not edit copied files by hand."
  echo
  echo "Source repository: Brick Directory"
  echo
  echo "OpenAPI mappings:"
  echo "- rebrickable.yaml <- backend/libs/rebrickable-client/src/main/resources/openapi/api-spec.yaml"
  echo "- brickset.yaml <- backend/libs/brickset-client/src/main/resources/openapi/api-spec.yaml"
  echo "- brickowl.yaml <- backend/libs/brickowl-client/src/main/resources/openapi/api-spec.yaml"
  echo "- bricklink.yaml <- backend/libs/bricklink-client/src/main/resources/openapi/api-spec.yaml"
  echo "- brickeconomy.yaml <- backend/libs/brickeconomy-client/src/main/resources/openapi/api-spec.yaml"
  echo
  echo "Prompt mappings:"
  echo "- prompts/*.txt <- backend/apps/brick-directory-mcp-server/src/main/resources/prompts/*.txt"
} > "$REPO_ROOT/references/SOURCE.md"

(
  cd "$REPO_ROOT"
  find references/openapi references/prompts -type f \( -name '*.yaml' -o -name '*.txt' \) -print0 \
    | sort -z \
    | xargs -0 sha256sum
) > "$REPO_ROOT/references/SHA256SUMS"

echo "Synced OpenAPI specs and prompts from $SOURCE_ROOT"
